FROM python:3.11-slim
WORKDIR /app
COPY requirements_ws.txt .
RUN pip install --no-cache-dir -r requirements_ws.txt
COPY websocket_chat.py .
EXPOSE 8003
CMD ["uvicorn","websocket_chat:app","--host","0.0.0.0","--port","8003"]
